version: '3.3'
networks:
  lemp-network:
services:
   nginx:
     depends_on:
       - php
     image: nginx:alpine
     networks:
       - lemp-network
     volumes:
       - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
       - ./www:/var/www/html
     ports:
       - "8008:80"
     restart: always

   php:
     container_name: php
     image: chialab/php:7.3-fpm
     networks:
       - lemp-network
     restart: always
     volumes:
       - ./www/:/var/www/html
     ports:
       - "9009:9000"
     expose:
       - "9000"
